# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e8f67cd227cbc97fcf16a255db8671cf3053b9da91f3e4fe5c9b95d93323d7673e9757c5060ba35c6ec561984036706ed6bda89428b0c88b722b088e98d7dad1

test:
  secret_key_base: 58cfa53e615375f190851d350a049688f149ec2727da1f4e82d0012ef140841b135df1c728fff31adb50c4be5e9db7bcbc964c7ea0809fee6d0f00ab8018725d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
